spring.application.name=requesttracker

spring.mongodb.uri=mongodb://mongodb-service:27017/requestdb
server.port=8080

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Prometheus endpoint
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true